### ISSUE TITLE
International Tickers 

### ISSUE THREAD

**Issue by Micky-G** [stephszeto/stocks#1]
python3 valuation.py -t BP.L
python3 valuation.py -t BARC.L
python3 valuation.py -t RDS.B

Produce the following error:

Fetching industries data ... 
Processing TICKER
Traceback (most recent call last):
  File "valuation.py", line 738, in <module>
    print_industry_tickers(ticker)
  File "valuation.py", line 63, in print_industry_tickers
    industry = company_vals[ticker]['industry']
KeyError: 'TICKER'

**Comment by Micky-G** [comment]
It is a bit of a shame but does not look like financial modelling prep actually supports the LSE. 
These are the exchanges they support : nyse - nasdaq - amex - euronex - tsx - etf - mutual_fund
Bummer! Thanks for all your hard work.

**Comment by girmax** [comment]
Instead of RDS.B --> use RDS-B, instead of BP.L --> use BP, ect. it worked for me.

**Comment by stephszeto** [comment]
There is also BCS for Barclays, although note that it's the US ADR for BARC.L so it's not quite a 1:1 replacement.

**Comment by girmax** [comment]
> There is also BCS for Barclays, although note that it's the US ADR for BARC.L so it's not quite a 1:1 replacement.

FYI, free API only cover the US stocks https://financialmodelingprep.com. You need a paid subscription if you want stocks outside the US.

**Comment by Micky-G** [comment]
> > There is also BCS for Barclays, although note that it's the US ADR for BARC.L so it's not quite a 1:1 replacement.
> 
> FYI, free API only cover the US stocks https://financialmodelingprep.com. You need a paid subscription if you want stocks outside the US.

I do have a paid for subscription, I think its more that https://financialmodelingprep.com does not cover the LSE which is a bit of a shame. I will need to try and find an alternative source of data. It does not take away from all the hard work that has been done which I am very thankful for.

**Comment by antoinevulcain** [comment]
Hello @Micky-G they do cover LSE:

**Comment by antoinevulcain** [comment]
Hello @Micky-G

**Comment by antoinevulcain** [comment]
Hello @Micky-G ,

They do cover LSE:

https://financialmodelingprep.com/api/v3/income-statement/BARC.L?period=quarter&limit=40&apikey=

You can see all the market covered here:

https://financialmodelingprep.com/developer/docs/#International-Filings
